package com.hongikgrad.major.dto;

public enum MajorCode {
	EE, CE, ME, CIVIL, IE, MSE, CHEMENG,
	ARCH1, ARCH2, URBAN,
	BIZADMIN,
	ENGLISH, GERMAN, FRANCE, KOREAN,
	LAW,
	MATHEDU, KOREDU, ENGEDU, HISEDU, EDU,
	ORIP, PAINTING, PRINTMK, SCU, WAF, ART, METALART, CER, TAFD, SIDI, ID,
	ECONOMICS,
}
